// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: post/v1/post.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PostStatus 定义了帖子的状态枚举类型，包括草稿、已发布和已归档三种状态
type PostStatus int32

const (
	PostStatus_DRAFT     PostStatus = 0 // 草稿
	PostStatus_PUBLISHED PostStatus = 1 // 已发布
	PostStatus_ARCHIVED  PostStatus = 2 // 已归档
)

// Enum value maps for PostStatus.
var (
	PostStatus_name = map[int32]string{
		0: "DRAFT",
		1: "PUBLISHED",
		2: "ARCHIVED",
	}
	PostStatus_value = map[string]int32{
		"DRAFT":     0,
		"PUBLISHED": 1,
		"ARCHIVED":  2,
	}
)

func (x PostStatus) Enum() *PostStatus {
	p := new(PostStatus)
	*p = x
	return p
}

func (x PostStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_post_v1_post_proto_enumTypes[0].Descriptor()
}

func (PostStatus) Type() protoreflect.EnumType {
	return &file_post_v1_post_proto_enumTypes[0]
}

func (x PostStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostStatus.Descriptor instead.
func (PostStatus) EnumDescriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{0}
}

type AuthorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                               // 作者ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                            // 作者姓名
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 作者头像URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorInfo) Reset() {
	*x = AuthorInfo{}
	mi := &file_post_v1_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorInfo) ProtoMessage() {}

func (x *AuthorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorInfo.ProtoReflect.Descriptor instead.
func (*AuthorInfo) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuthorInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthorInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type CategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // 分类ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 分类名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInfo) Reset() {
	*x = CategoryInfo{}
	mi := &file_post_v1_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfo) ProtoMessage() {}

func (x *CategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfo.ProtoReflect.Descriptor instead.
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// PostInfo 包含了帖子的基本信息
type PostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                         // 帖子ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                    // 帖子标题
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`                                // 帖子摘要
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`                                      // 帖子URL友好标识
	Status        PostStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=api.post.v1.PostStatus" json:"status,omitempty"`     // 帖子状态
	ViewCount     int64                  `protobuf:"varint,6,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`          // 浏览量
	LikeCount     int64                  `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`          // 点赞量
	CommentCount  int64                  `protobuf:"varint,8,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"` // 评论量
	Author        *AuthorInfo            `protobuf:"bytes,9,opt,name=author,proto3" json:"author,omitempty"`                                  // 作者信息
	Category      *CategoryInfo          `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`                             // 分类信息
	Tags          []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`                                     // 标签列表
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfo) Reset() {
	*x = PostInfo{}
	mi := &file_post_v1_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfo) ProtoMessage() {}

func (x *PostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfo.ProtoReflect.Descriptor instead.
func (*PostInfo) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{2}
}

func (x *PostInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PostInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PostInfo) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_DRAFT
}

func (x *PostInfo) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *PostInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *PostInfo) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *PostInfo) GetAuthor() *AuthorInfo {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *PostInfo) GetCategory() *CategoryInfo {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *PostInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PostInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PostInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// PostDetail 包含了帖子的详细信息，在PostInfo的基础上增加了正文内容字段content
type PostDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Info            *PostInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`                                              // 帖子基本信息
	Content         string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                        // 帖子正文
	OriginalContent string                 `protobuf:"bytes,3,opt,name=original_content,json=originalContent,proto3" json:"original_content,omitempty"` // 帖子原始内容（Markdown格式）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PostDetail) Reset() {
	*x = PostDetail{}
	mi := &file_post_v1_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDetail) ProtoMessage() {}

func (x *PostDetail) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDetail.ProtoReflect.Descriptor instead.
func (*PostDetail) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{3}
}

func (x *PostDetail) GetInfo() *PostInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *PostDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostDetail) GetOriginalContent() string {
	if x != nil {
		return x.OriginalContent
	}
	return ""
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                // 帖子标题
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`                            // 帖子摘要
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`                                  // 帖子URL友好标识
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                            // 帖子正文
	Status        PostStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=api.post.v1.PostStatus" json:"status,omitempty"` // 帖子状态
	CategoryId    int64                  `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`   // 分类ID
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`                                  // 标签列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_post_v1_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreatePostRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_DRAFT
}

func (x *CreatePostRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreatePostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreatePostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *PostDetail            `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"` // 创建成功后返回的帖子详细信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReply) Reset() {
	*x = CreatePostReply{}
	mi := &file_post_v1_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReply) ProtoMessage() {}

func (x *CreatePostReply) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReply.ProtoReflect.Descriptor instead.
func (*CreatePostReply) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePostReply) GetPost() *PostDetail {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     // 帖子ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                // 帖子标题
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`                            // 帖子摘要
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`                                  // 帖子URL友好标识
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                            // 帖子正文
	Status        PostStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=api.post.v1.PostStatus" json:"status,omitempty"` // 帖子状态
	CategoryId    int64                  `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`   // 分类ID
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`                                  // 标签列表
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,9,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`    // 指定要更新的字段列表，例如 "title,summary,content" 表示只更新标题、摘要和正文内容，其他字段保持不变
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_post_v1_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdatePostRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdatePostRequest) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_DRAFT
}

func (x *UpdatePostRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdatePostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdatePostRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdatePostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *PostDetail            `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"` // 更新成功后返回的帖子详细信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostReply) Reset() {
	*x = UpdatePostReply{}
	mi := &file_post_v1_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostReply) ProtoMessage() {}

func (x *UpdatePostReply) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostReply.ProtoReflect.Descriptor instead.
func (*UpdatePostReply) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePostReply) GetPost() *PostDetail {
	if x != nil {
		return x.Post
	}
	return nil
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 帖子ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_post_v1_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 删除是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostReply) Reset() {
	*x = DeletePostReply{}
	mi := &file_post_v1_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostReply) ProtoMessage() {}

func (x *DeletePostReply) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostReply.ProtoReflect.Descriptor instead.
func (*DeletePostReply) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePostReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Query:
	//
	//	*GetPostRequest_Id
	//	*GetPostRequest_Slug
	Query         isGetPostRequest_Query `protobuf_oneof:"query"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_post_v1_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{10}
}

func (x *GetPostRequest) GetQuery() isGetPostRequest_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *GetPostRequest) GetId() int64 {
	if x != nil {
		if x, ok := x.Query.(*GetPostRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *GetPostRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Query.(*GetPostRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

type isGetPostRequest_Query interface {
	isGetPostRequest_Query()
}

type GetPostRequest_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3,oneof"` // 通过帖子ID查询
}

type GetPostRequest_Slug struct {
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"` // 通过帖子slug查询
}

func (*GetPostRequest_Id) isGetPostRequest_Query() {}

func (*GetPostRequest_Slug) isGetPostRequest_Query() {}

type GetPostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *PostDetail            `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostReply) Reset() {
	*x = GetPostReply{}
	mi := &file_post_v1_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostReply) ProtoMessage() {}

func (x *GetPostReply) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostReply.ProtoReflect.Descriptor instead.
func (*GetPostReply) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{11}
}

func (x *GetPostReply) GetPost() *PostDetail {
	if x != nil {
		return x.Post
	}
	return nil
}

type ListPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostRequest) Reset() {
	*x = ListPostRequest{}
	mi := &file_post_v1_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostRequest) ProtoMessage() {}

func (x *ListPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostRequest.ProtoReflect.Descriptor instead.
func (*ListPostRequest) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{12}
}

func (x *ListPostRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPostRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostInfo            `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`  // 帖子列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总帖子数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostReply) Reset() {
	*x = ListPostReply{}
	mi := &file_post_v1_post_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostReply) ProtoMessage() {}

func (x *ListPostReply) ProtoReflect() protoreflect.Message {
	mi := &file_post_v1_post_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostReply.ProtoReflect.Descriptor instead.
func (*ListPostReply) Descriptor() ([]byte, []int) {
	return file_post_v1_post_proto_rawDescGZIP(), []int{13}
}

func (x *ListPostReply) GetPosts() []*PostInfo {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListPostReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_post_v1_post_proto protoreflect.FileDescriptor

const file_post_v1_post_proto_rawDesc = "" +
	"\n" +
	"\x12post/v1/post.proto\x12\vapi.post.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"O\n" +
	"\n" +
	"AuthorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"2\n" +
	"\fCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe4\x03\n" +
	"\bPostInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.api.post.v1.PostStatusR\x06status\x12\x1d\n" +
	"\n" +
	"view_count\x18\x06 \x01(\x03R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\b \x01(\x03R\fcommentCount\x12/\n" +
	"\x06author\x18\t \x01(\v2\x17.api.post.v1.AuthorInfoR\x06author\x125\n" +
	"\bcategory\x18\n" +
	" \x01(\v2\x19.api.post.v1.CategoryInfoR\bcategory\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"|\n" +
	"\n" +
	"PostDetail\x12)\n" +
	"\x04info\x18\x01 \x01(\v2\x15.api.post.v1.PostInfoR\x04info\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12)\n" +
	"\x10original_content\x18\x03 \x01(\tR\x0foriginalContent\"\xd7\x01\n" +
	"\x11CreatePostRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.api.post.v1.PostStatusR\x06status\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\">\n" +
	"\x0fCreatePostReply\x12+\n" +
	"\x04post\x18\x01 \x01(\v2\x17.api.post.v1.PostDetailR\x04post\"\xa4\x02\n" +
	"\x11UpdatePostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12/\n" +
	"\x06status\x18\x06 \x01(\x0e2\x17.api.post.v1.PostStatusR\x06status\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12;\n" +
	"\vupdate_mask\x18\t \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\">\n" +
	"\x0fUpdatePostReply\x12+\n" +
	"\x04post\x18\x01 \x01(\v2\x17.api.post.v1.PostDetailR\x04post\"#\n" +
	"\x11DeletePostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"+\n" +
	"\x0fDeletePostReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\x0eGetPostRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slugB\a\n" +
	"\x05query\";\n" +
	"\fGetPostReply\x12+\n" +
	"\x04post\x18\x01 \x01(\v2\x17.api.post.v1.PostDetailR\x04post\"B\n" +
	"\x0fListPostRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"R\n" +
	"\rListPostReply\x12+\n" +
	"\x05posts\x18\x01 \x03(\v2\x15.api.post.v1.PostInfoR\x05posts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total*4\n" +
	"\n" +
	"PostStatus\x12\t\n" +
	"\x05DRAFT\x10\x00\x12\r\n" +
	"\tPUBLISHED\x10\x01\x12\f\n" +
	"\bARCHIVED\x10\x022\x80\x04\n" +
	"\x04Post\x12`\n" +
	"\n" +
	"CreatePost\x12\x1e.api.post.v1.CreatePostRequest\x1a\x1c.api.post.v1.CreatePostReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/posts\x12e\n" +
	"\n" +
	"UpdatePost\x12\x1e.api.post.v1.UpdatePostRequest\x1a\x1c.api.post.v1.UpdatePostReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*2\x0e/v1/posts/{id}\x12b\n" +
	"\n" +
	"DeletePost\x12\x1e.api.post.v1.DeletePostRequest\x1a\x1c.api.post.v1.DeletePostReply\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/posts/{id}\x12r\n" +
	"\aGetPost\x12\x1b.api.post.v1.GetPostRequest\x1a\x19.api.post.v1.GetPostReply\"/\x82\xd3\xe4\x93\x02)Z\x17\x12\x15/v1/posts/slug/{slug}\x12\x0e/v1/posts/{id}\x12W\n" +
	"\bListPost\x12\x1c.api.post.v1.ListPostRequest\x1a\x1a.api.post.v1.ListPostReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/postsB)\n" +
	"\vapi.post.v1P\x01Z\x18GoPalette/api/post/v1;v1b\x06proto3"

var (
	file_post_v1_post_proto_rawDescOnce sync.Once
	file_post_v1_post_proto_rawDescData []byte
)

func file_post_v1_post_proto_rawDescGZIP() []byte {
	file_post_v1_post_proto_rawDescOnce.Do(func() {
		file_post_v1_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_v1_post_proto_rawDesc), len(file_post_v1_post_proto_rawDesc)))
	})
	return file_post_v1_post_proto_rawDescData
}

var file_post_v1_post_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_post_v1_post_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_post_v1_post_proto_goTypes = []any{
	(PostStatus)(0),               // 0: api.post.v1.PostStatus
	(*AuthorInfo)(nil),            // 1: api.post.v1.AuthorInfo
	(*CategoryInfo)(nil),          // 2: api.post.v1.CategoryInfo
	(*PostInfo)(nil),              // 3: api.post.v1.PostInfo
	(*PostDetail)(nil),            // 4: api.post.v1.PostDetail
	(*CreatePostRequest)(nil),     // 5: api.post.v1.CreatePostRequest
	(*CreatePostReply)(nil),       // 6: api.post.v1.CreatePostReply
	(*UpdatePostRequest)(nil),     // 7: api.post.v1.UpdatePostRequest
	(*UpdatePostReply)(nil),       // 8: api.post.v1.UpdatePostReply
	(*DeletePostRequest)(nil),     // 9: api.post.v1.DeletePostRequest
	(*DeletePostReply)(nil),       // 10: api.post.v1.DeletePostReply
	(*GetPostRequest)(nil),        // 11: api.post.v1.GetPostRequest
	(*GetPostReply)(nil),          // 12: api.post.v1.GetPostReply
	(*ListPostRequest)(nil),       // 13: api.post.v1.ListPostRequest
	(*ListPostReply)(nil),         // 14: api.post.v1.ListPostReply
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 16: google.protobuf.FieldMask
}
var file_post_v1_post_proto_depIdxs = []int32{
	0,  // 0: api.post.v1.PostInfo.status:type_name -> api.post.v1.PostStatus
	1,  // 1: api.post.v1.PostInfo.author:type_name -> api.post.v1.AuthorInfo
	2,  // 2: api.post.v1.PostInfo.category:type_name -> api.post.v1.CategoryInfo
	15, // 3: api.post.v1.PostInfo.created_at:type_name -> google.protobuf.Timestamp
	15, // 4: api.post.v1.PostInfo.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 5: api.post.v1.PostDetail.info:type_name -> api.post.v1.PostInfo
	0,  // 6: api.post.v1.CreatePostRequest.status:type_name -> api.post.v1.PostStatus
	4,  // 7: api.post.v1.CreatePostReply.post:type_name -> api.post.v1.PostDetail
	0,  // 8: api.post.v1.UpdatePostRequest.status:type_name -> api.post.v1.PostStatus
	16, // 9: api.post.v1.UpdatePostRequest.update_mask:type_name -> google.protobuf.FieldMask
	4,  // 10: api.post.v1.UpdatePostReply.post:type_name -> api.post.v1.PostDetail
	4,  // 11: api.post.v1.GetPostReply.post:type_name -> api.post.v1.PostDetail
	3,  // 12: api.post.v1.ListPostReply.posts:type_name -> api.post.v1.PostInfo
	5,  // 13: api.post.v1.Post.CreatePost:input_type -> api.post.v1.CreatePostRequest
	7,  // 14: api.post.v1.Post.UpdatePost:input_type -> api.post.v1.UpdatePostRequest
	9,  // 15: api.post.v1.Post.DeletePost:input_type -> api.post.v1.DeletePostRequest
	11, // 16: api.post.v1.Post.GetPost:input_type -> api.post.v1.GetPostRequest
	13, // 17: api.post.v1.Post.ListPost:input_type -> api.post.v1.ListPostRequest
	6,  // 18: api.post.v1.Post.CreatePost:output_type -> api.post.v1.CreatePostReply
	8,  // 19: api.post.v1.Post.UpdatePost:output_type -> api.post.v1.UpdatePostReply
	10, // 20: api.post.v1.Post.DeletePost:output_type -> api.post.v1.DeletePostReply
	12, // 21: api.post.v1.Post.GetPost:output_type -> api.post.v1.GetPostReply
	14, // 22: api.post.v1.Post.ListPost:output_type -> api.post.v1.ListPostReply
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_post_v1_post_proto_init() }
func file_post_v1_post_proto_init() {
	if File_post_v1_post_proto != nil {
		return
	}
	file_post_v1_post_proto_msgTypes[10].OneofWrappers = []any{
		(*GetPostRequest_Id)(nil),
		(*GetPostRequest_Slug)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_v1_post_proto_rawDesc), len(file_post_v1_post_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_v1_post_proto_goTypes,
		DependencyIndexes: file_post_v1_post_proto_depIdxs,
		EnumInfos:         file_post_v1_post_proto_enumTypes,
		MessageInfos:      file_post_v1_post_proto_msgTypes,
	}.Build()
	File_post_v1_post_proto = out.File
	file_post_v1_post_proto_goTypes = nil
	file_post_v1_post_proto_depIdxs = nil
}
