// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: post/v1/post.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPostCreatePost = "/api.post.v1.Post/CreatePost"
const OperationPostDeletePost = "/api.post.v1.Post/DeletePost"
const OperationPostGetAuthorPostStats = "/api.post.v1.Post/GetAuthorPostStats"
const OperationPostGetPost = "/api.post.v1.Post/GetPost"
const OperationPostGetPostLikeState = "/api.post.v1.Post/GetPostLikeState"
const OperationPostListAuthorPosts = "/api.post.v1.Post/ListAuthorPosts"
const OperationPostListPosts = "/api.post.v1.Post/ListPosts"
const OperationPostListTopAuthorPosts = "/api.post.v1.Post/ListTopAuthorPosts"
const OperationPostListUserLikedPosts = "/api.post.v1.Post/ListUserLikedPosts"
const OperationPostRecordPostView = "/api.post.v1.Post/RecordPostView"
const OperationPostTogglePostLike = "/api.post.v1.Post/TogglePostLike"
const OperationPostUpdatePost = "/api.post.v1.Post/UpdatePost"

type PostHTTPServer interface {
	// CreatePost CreatePost 创建帖子，输入帖子标题、摘要、正文内容、状态、作者ID、分类ID和标签列表，返回创建的帖子详细信息
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostReply, error)
	// DeletePost DeletePost 删除帖子，输入帖子ID，返回删除是否成功
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostReply, error)
	// GetAuthorPostStats GetAuthorPostStats 获取作者帖子聚合统计
	GetAuthorPostStats(context.Context, *GetAuthorPostStatsRequest) (*GetAuthorPostStatsReply, error)
	// GetPost GetPost 获取帖子，输入帖子ID或slug，返回帖子详细信息
	GetPost(context.Context, *GetPostRequest) (*GetPostReply, error)
	// GetPostLikeState GetPostLikeState 获取当前用户对文章的点赞状态
	GetPostLikeState(context.Context, *GetPostLikeStateRequest) (*GetPostLikeStateReply, error)
	// ListAuthorPosts ListAuthorPosts 按作者列出帖子（用于个人主页）
	ListAuthorPosts(context.Context, *ListAuthorPostsRequest) (*ListAuthorPostsReply, error)
	// ListPosts ListPosts 列出帖子，输入分页参数，返回帖子列表
	ListPosts(context.Context, *ListPostsRequest) (*ListPostsReply, error)
	// ListTopAuthorPosts ListTopAuthorPosts 获取作者热门文章
	ListTopAuthorPosts(context.Context, *ListTopAuthorPostsRequest) (*ListTopAuthorPostsReply, error)
	// ListUserLikedPosts ListUserLikedPosts 获取用户点赞/收藏文章列表
	ListUserLikedPosts(context.Context, *ListUserLikedPostsRequest) (*ListUserLikedPostsReply, error)
	// RecordPostView RecordPostView 记录文章浏览，服务端按 viewer_key 去重后自增浏览量
	RecordPostView(context.Context, *RecordPostViewRequest) (*RecordPostViewReply, error)
	// TogglePostLike TogglePostLike 点赞/取消点赞
	TogglePostLike(context.Context, *TogglePostLikeRequest) (*TogglePostLikeReply, error)
	// UpdatePost UpdatePost 更新帖子，输入帖子ID和要更新的字段列表，返回更新后的帖子详细信息
	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostReply, error)
}

func RegisterPostHTTPServer(s *http.Server, srv PostHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/posts", _Post_CreatePost0_HTTP_Handler(srv))
	r.PATCH("/v1/posts/{id}", _Post_UpdatePost0_HTTP_Handler(srv))
	r.DELETE("/v1/posts/{id}", _Post_DeletePost0_HTTP_Handler(srv))
	r.GET("/v1/posts/slug/{slug}", _Post_GetPost0_HTTP_Handler(srv))
	r.GET("/v1/posts/{id}", _Post_GetPost1_HTTP_Handler(srv))
	r.GET("/v1/posts", _Post_ListPosts0_HTTP_Handler(srv))
	r.GET("/v1/users/{author_id}/posts", _Post_ListAuthorPosts0_HTTP_Handler(srv))
	r.GET("/v1/users/{author_id}/posts/stats", _Post_GetAuthorPostStats0_HTTP_Handler(srv))
	r.GET("/v1/users/{author_id}/posts/top", _Post_ListTopAuthorPosts0_HTTP_Handler(srv))
	r.POST("/v1/posts/{id}/view", _Post_RecordPostView0_HTTP_Handler(srv))
	r.POST("/v1/posts/{id}/like", _Post_TogglePostLike0_HTTP_Handler(srv))
	r.GET("/v1/posts/{id}/like-state", _Post_GetPostLikeState0_HTTP_Handler(srv))
	r.GET("/v1/users/{user_id}/likes", _Post_ListUserLikedPosts0_HTTP_Handler(srv))
}

func _Post_CreatePost0_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePostRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostCreatePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePost(ctx, req.(*CreatePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePostReply)
		return ctx.Result(200, reply)
	}
}

func _Post_UpdatePost0_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePostRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostUpdatePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePost(ctx, req.(*UpdatePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePostReply)
		return ctx.Result(200, reply)
	}
}

func _Post_DeletePost0_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePostRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostDeletePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePost(ctx, req.(*DeletePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeletePostReply)
		return ctx.Result(200, reply)
	}
}

func _Post_GetPost0_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPostRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostGetPost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPost(ctx, req.(*GetPostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPostReply)
		return ctx.Result(200, reply)
	}
}

func _Post_GetPost1_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPostRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostGetPost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPost(ctx, req.(*GetPostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPostReply)
		return ctx.Result(200, reply)
	}
}

func _Post_ListPosts0_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPostsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostListPosts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPosts(ctx, req.(*ListPostsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPostsReply)
		return ctx.Result(200, reply)
	}
}

func _Post_ListAuthorPosts0_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAuthorPostsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostListAuthorPosts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAuthorPosts(ctx, req.(*ListAuthorPostsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAuthorPostsReply)
		return ctx.Result(200, reply)
	}
}

func _Post_GetAuthorPostStats0_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAuthorPostStatsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostGetAuthorPostStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAuthorPostStats(ctx, req.(*GetAuthorPostStatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAuthorPostStatsReply)
		return ctx.Result(200, reply)
	}
}

func _Post_ListTopAuthorPosts0_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTopAuthorPostsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostListTopAuthorPosts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTopAuthorPosts(ctx, req.(*ListTopAuthorPostsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTopAuthorPostsReply)
		return ctx.Result(200, reply)
	}
}

func _Post_RecordPostView0_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RecordPostViewRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostRecordPostView)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RecordPostView(ctx, req.(*RecordPostViewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RecordPostViewReply)
		return ctx.Result(200, reply)
	}
}

func _Post_TogglePostLike0_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TogglePostLikeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostTogglePostLike)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TogglePostLike(ctx, req.(*TogglePostLikeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TogglePostLikeReply)
		return ctx.Result(200, reply)
	}
}

func _Post_GetPostLikeState0_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPostLikeStateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostGetPostLikeState)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPostLikeState(ctx, req.(*GetPostLikeStateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPostLikeStateReply)
		return ctx.Result(200, reply)
	}
}

func _Post_ListUserLikedPosts0_HTTP_Handler(srv PostHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUserLikedPostsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPostListUserLikedPosts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUserLikedPosts(ctx, req.(*ListUserLikedPostsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUserLikedPostsReply)
		return ctx.Result(200, reply)
	}
}

type PostHTTPClient interface {
	// CreatePost CreatePost 创建帖子，输入帖子标题、摘要、正文内容、状态、作者ID、分类ID和标签列表，返回创建的帖子详细信息
	CreatePost(ctx context.Context, req *CreatePostRequest, opts ...http.CallOption) (rsp *CreatePostReply, err error)
	// DeletePost DeletePost 删除帖子，输入帖子ID，返回删除是否成功
	DeletePost(ctx context.Context, req *DeletePostRequest, opts ...http.CallOption) (rsp *DeletePostReply, err error)
	// GetAuthorPostStats GetAuthorPostStats 获取作者帖子聚合统计
	GetAuthorPostStats(ctx context.Context, req *GetAuthorPostStatsRequest, opts ...http.CallOption) (rsp *GetAuthorPostStatsReply, err error)
	// GetPost GetPost 获取帖子，输入帖子ID或slug，返回帖子详细信息
	GetPost(ctx context.Context, req *GetPostRequest, opts ...http.CallOption) (rsp *GetPostReply, err error)
	// GetPostLikeState GetPostLikeState 获取当前用户对文章的点赞状态
	GetPostLikeState(ctx context.Context, req *GetPostLikeStateRequest, opts ...http.CallOption) (rsp *GetPostLikeStateReply, err error)
	// ListAuthorPosts ListAuthorPosts 按作者列出帖子（用于个人主页）
	ListAuthorPosts(ctx context.Context, req *ListAuthorPostsRequest, opts ...http.CallOption) (rsp *ListAuthorPostsReply, err error)
	// ListPosts ListPosts 列出帖子，输入分页参数，返回帖子列表
	ListPosts(ctx context.Context, req *ListPostsRequest, opts ...http.CallOption) (rsp *ListPostsReply, err error)
	// ListTopAuthorPosts ListTopAuthorPosts 获取作者热门文章
	ListTopAuthorPosts(ctx context.Context, req *ListTopAuthorPostsRequest, opts ...http.CallOption) (rsp *ListTopAuthorPostsReply, err error)
	// ListUserLikedPosts ListUserLikedPosts 获取用户点赞/收藏文章列表
	ListUserLikedPosts(ctx context.Context, req *ListUserLikedPostsRequest, opts ...http.CallOption) (rsp *ListUserLikedPostsReply, err error)
	// RecordPostView RecordPostView 记录文章浏览，服务端按 viewer_key 去重后自增浏览量
	RecordPostView(ctx context.Context, req *RecordPostViewRequest, opts ...http.CallOption) (rsp *RecordPostViewReply, err error)
	// TogglePostLike TogglePostLike 点赞/取消点赞
	TogglePostLike(ctx context.Context, req *TogglePostLikeRequest, opts ...http.CallOption) (rsp *TogglePostLikeReply, err error)
	// UpdatePost UpdatePost 更新帖子，输入帖子ID和要更新的字段列表，返回更新后的帖子详细信息
	UpdatePost(ctx context.Context, req *UpdatePostRequest, opts ...http.CallOption) (rsp *UpdatePostReply, err error)
}

type PostHTTPClientImpl struct {
	cc *http.Client
}

func NewPostHTTPClient(client *http.Client) PostHTTPClient {
	return &PostHTTPClientImpl{client}
}

// CreatePost CreatePost 创建帖子，输入帖子标题、摘要、正文内容、状态、作者ID、分类ID和标签列表，返回创建的帖子详细信息
func (c *PostHTTPClientImpl) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...http.CallOption) (*CreatePostReply, error) {
	var out CreatePostReply
	pattern := "/v1/posts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPostCreatePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeletePost DeletePost 删除帖子，输入帖子ID，返回删除是否成功
func (c *PostHTTPClientImpl) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...http.CallOption) (*DeletePostReply, error) {
	var out DeletePostReply
	pattern := "/v1/posts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPostDeletePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAuthorPostStats GetAuthorPostStats 获取作者帖子聚合统计
func (c *PostHTTPClientImpl) GetAuthorPostStats(ctx context.Context, in *GetAuthorPostStatsRequest, opts ...http.CallOption) (*GetAuthorPostStatsReply, error) {
	var out GetAuthorPostStatsReply
	pattern := "/v1/users/{author_id}/posts/stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPostGetAuthorPostStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPost GetPost 获取帖子，输入帖子ID或slug，返回帖子详细信息
func (c *PostHTTPClientImpl) GetPost(ctx context.Context, in *GetPostRequest, opts ...http.CallOption) (*GetPostReply, error) {
	var out GetPostReply
	pattern := "/v1/posts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPostGetPost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPostLikeState GetPostLikeState 获取当前用户对文章的点赞状态
func (c *PostHTTPClientImpl) GetPostLikeState(ctx context.Context, in *GetPostLikeStateRequest, opts ...http.CallOption) (*GetPostLikeStateReply, error) {
	var out GetPostLikeStateReply
	pattern := "/v1/posts/{id}/like-state"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPostGetPostLikeState))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAuthorPosts ListAuthorPosts 按作者列出帖子（用于个人主页）
func (c *PostHTTPClientImpl) ListAuthorPosts(ctx context.Context, in *ListAuthorPostsRequest, opts ...http.CallOption) (*ListAuthorPostsReply, error) {
	var out ListAuthorPostsReply
	pattern := "/v1/users/{author_id}/posts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPostListAuthorPosts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPosts ListPosts 列出帖子，输入分页参数，返回帖子列表
func (c *PostHTTPClientImpl) ListPosts(ctx context.Context, in *ListPostsRequest, opts ...http.CallOption) (*ListPostsReply, error) {
	var out ListPostsReply
	pattern := "/v1/posts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPostListPosts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTopAuthorPosts ListTopAuthorPosts 获取作者热门文章
func (c *PostHTTPClientImpl) ListTopAuthorPosts(ctx context.Context, in *ListTopAuthorPostsRequest, opts ...http.CallOption) (*ListTopAuthorPostsReply, error) {
	var out ListTopAuthorPostsReply
	pattern := "/v1/users/{author_id}/posts/top"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPostListTopAuthorPosts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListUserLikedPosts ListUserLikedPosts 获取用户点赞/收藏文章列表
func (c *PostHTTPClientImpl) ListUserLikedPosts(ctx context.Context, in *ListUserLikedPostsRequest, opts ...http.CallOption) (*ListUserLikedPostsReply, error) {
	var out ListUserLikedPostsReply
	pattern := "/v1/users/{user_id}/likes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPostListUserLikedPosts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RecordPostView RecordPostView 记录文章浏览，服务端按 viewer_key 去重后自增浏览量
func (c *PostHTTPClientImpl) RecordPostView(ctx context.Context, in *RecordPostViewRequest, opts ...http.CallOption) (*RecordPostViewReply, error) {
	var out RecordPostViewReply
	pattern := "/v1/posts/{id}/view"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPostRecordPostView))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TogglePostLike TogglePostLike 点赞/取消点赞
func (c *PostHTTPClientImpl) TogglePostLike(ctx context.Context, in *TogglePostLikeRequest, opts ...http.CallOption) (*TogglePostLikeReply, error) {
	var out TogglePostLikeReply
	pattern := "/v1/posts/{id}/like"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPostTogglePostLike))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePost UpdatePost 更新帖子，输入帖子ID和要更新的字段列表，返回更新后的帖子详细信息
func (c *PostHTTPClientImpl) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...http.CallOption) (*UpdatePostReply, error) {
	var out UpdatePostReply
	pattern := "/v1/posts/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPostUpdatePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationCategoryCreateCategory = "/api.post.v1.Category/CreateCategory"
const OperationCategoryDeleteCategory = "/api.post.v1.Category/DeleteCategory"
const OperationCategoryGetCategory = "/api.post.v1.Category/GetCategory"
const OperationCategoryListCategories = "/api.post.v1.Category/ListCategories"
const OperationCategoryUpdateCategory = "/api.post.v1.Category/UpdateCategory"

type CategoryHTTPServer interface {
	// CreateCategory CreateCategory 创建分类
	CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryReply, error)
	// DeleteCategory DeleteCategory 删除分类
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryReply, error)
	// GetCategory GetCategory 获取分类详情
	GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryReply, error)
	// ListCategories ListCategories 列出分类，输入分页参数，返回分类列表
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesReply, error)
	// UpdateCategory UpdateCategory 更新分类
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryReply, error)
}

func RegisterCategoryHTTPServer(s *http.Server, srv CategoryHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/categories", _Category_CreateCategory0_HTTP_Handler(srv))
	r.PATCH("/v1/categories/{id}", _Category_UpdateCategory0_HTTP_Handler(srv))
	r.DELETE("/v1/categories/{id}", _Category_DeleteCategory0_HTTP_Handler(srv))
	r.GET("/v1/categories/{id}", _Category_GetCategory0_HTTP_Handler(srv))
	r.GET("/v1/categories", _Category_ListCategories0_HTTP_Handler(srv))
}

func _Category_CreateCategory0_HTTP_Handler(srv CategoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCategoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCategoryCreateCategory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCategory(ctx, req.(*CreateCategoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateCategoryReply)
		return ctx.Result(200, reply)
	}
}

func _Category_UpdateCategory0_HTTP_Handler(srv CategoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCategoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCategoryUpdateCategory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCategory(ctx, req.(*UpdateCategoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCategoryReply)
		return ctx.Result(200, reply)
	}
}

func _Category_DeleteCategory0_HTTP_Handler(srv CategoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCategoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCategoryDeleteCategory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCategory(ctx, req.(*DeleteCategoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCategoryReply)
		return ctx.Result(200, reply)
	}
}

func _Category_GetCategory0_HTTP_Handler(srv CategoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCategoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCategoryGetCategory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCategory(ctx, req.(*GetCategoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCategoryReply)
		return ctx.Result(200, reply)
	}
}

func _Category_ListCategories0_HTTP_Handler(srv CategoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCategoriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCategoryListCategories)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCategories(ctx, req.(*ListCategoriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCategoriesReply)
		return ctx.Result(200, reply)
	}
}

type CategoryHTTPClient interface {
	// CreateCategory CreateCategory 创建分类
	CreateCategory(ctx context.Context, req *CreateCategoryRequest, opts ...http.CallOption) (rsp *CreateCategoryReply, err error)
	// DeleteCategory DeleteCategory 删除分类
	DeleteCategory(ctx context.Context, req *DeleteCategoryRequest, opts ...http.CallOption) (rsp *DeleteCategoryReply, err error)
	// GetCategory GetCategory 获取分类详情
	GetCategory(ctx context.Context, req *GetCategoryRequest, opts ...http.CallOption) (rsp *GetCategoryReply, err error)
	// ListCategories ListCategories 列出分类，输入分页参数，返回分类列表
	ListCategories(ctx context.Context, req *ListCategoriesRequest, opts ...http.CallOption) (rsp *ListCategoriesReply, err error)
	// UpdateCategory UpdateCategory 更新分类
	UpdateCategory(ctx context.Context, req *UpdateCategoryRequest, opts ...http.CallOption) (rsp *UpdateCategoryReply, err error)
}

type CategoryHTTPClientImpl struct {
	cc *http.Client
}

func NewCategoryHTTPClient(client *http.Client) CategoryHTTPClient {
	return &CategoryHTTPClientImpl{client}
}

// CreateCategory CreateCategory 创建分类
func (c *CategoryHTTPClientImpl) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...http.CallOption) (*CreateCategoryReply, error) {
	var out CreateCategoryReply
	pattern := "/v1/categories"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCategoryCreateCategory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteCategory DeleteCategory 删除分类
func (c *CategoryHTTPClientImpl) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...http.CallOption) (*DeleteCategoryReply, error) {
	var out DeleteCategoryReply
	pattern := "/v1/categories/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCategoryDeleteCategory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCategory GetCategory 获取分类详情
func (c *CategoryHTTPClientImpl) GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...http.CallOption) (*GetCategoryReply, error) {
	var out GetCategoryReply
	pattern := "/v1/categories/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCategoryGetCategory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCategories ListCategories 列出分类，输入分页参数，返回分类列表
func (c *CategoryHTTPClientImpl) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...http.CallOption) (*ListCategoriesReply, error) {
	var out ListCategoriesReply
	pattern := "/v1/categories"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCategoryListCategories))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCategory UpdateCategory 更新分类
func (c *CategoryHTTPClientImpl) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...http.CallOption) (*UpdateCategoryReply, error) {
	var out UpdateCategoryReply
	pattern := "/v1/categories/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCategoryUpdateCategory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationTagCreateTag = "/api.post.v1.Tag/CreateTag"
const OperationTagDeleteTag = "/api.post.v1.Tag/DeleteTag"
const OperationTagGetTag = "/api.post.v1.Tag/GetTag"
const OperationTagListTags = "/api.post.v1.Tag/ListTags"
const OperationTagUpdateTag = "/api.post.v1.Tag/UpdateTag"

type TagHTTPServer interface {
	// CreateTag CreateTag 创建标签
	CreateTag(context.Context, *CreateTagRequest) (*CreateTagReply, error)
	// DeleteTag DeleteTag 删除标签
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagReply, error)
	// GetTag GetTag 获取标签详情
	GetTag(context.Context, *GetTagRequest) (*GetTagReply, error)
	// ListTags ListTags 列出标签，输入分页参数，返回标签列表
	ListTags(context.Context, *ListTagsRequest) (*ListTagsReply, error)
	// UpdateTag UpdateTag 更新标签
	UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagReply, error)
}

func RegisterTagHTTPServer(s *http.Server, srv TagHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/tags", _Tag_CreateTag0_HTTP_Handler(srv))
	r.PATCH("/v1/tags/{id}", _Tag_UpdateTag0_HTTP_Handler(srv))
	r.DELETE("/v1/tags/{id}", _Tag_DeleteTag0_HTTP_Handler(srv))
	r.GET("/v1/tags/{id}", _Tag_GetTag0_HTTP_Handler(srv))
	r.GET("/v1/tags", _Tag_ListTags0_HTTP_Handler(srv))
}

func _Tag_CreateTag0_HTTP_Handler(srv TagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagCreateTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTag(ctx, req.(*CreateTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTagReply)
		return ctx.Result(200, reply)
	}
}

func _Tag_UpdateTag0_HTTP_Handler(srv TagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagUpdateTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTag(ctx, req.(*UpdateTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateTagReply)
		return ctx.Result(200, reply)
	}
}

func _Tag_DeleteTag0_HTTP_Handler(srv TagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTagRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagDeleteTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTag(ctx, req.(*DeleteTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteTagReply)
		return ctx.Result(200, reply)
	}
}

func _Tag_GetTag0_HTTP_Handler(srv TagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTagRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagGetTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTag(ctx, req.(*GetTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTagReply)
		return ctx.Result(200, reply)
	}
}

func _Tag_ListTags0_HTTP_Handler(srv TagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTagsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagListTags)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTags(ctx, req.(*ListTagsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTagsReply)
		return ctx.Result(200, reply)
	}
}

type TagHTTPClient interface {
	// CreateTag CreateTag 创建标签
	CreateTag(ctx context.Context, req *CreateTagRequest, opts ...http.CallOption) (rsp *CreateTagReply, err error)
	// DeleteTag DeleteTag 删除标签
	DeleteTag(ctx context.Context, req *DeleteTagRequest, opts ...http.CallOption) (rsp *DeleteTagReply, err error)
	// GetTag GetTag 获取标签详情
	GetTag(ctx context.Context, req *GetTagRequest, opts ...http.CallOption) (rsp *GetTagReply, err error)
	// ListTags ListTags 列出标签，输入分页参数，返回标签列表
	ListTags(ctx context.Context, req *ListTagsRequest, opts ...http.CallOption) (rsp *ListTagsReply, err error)
	// UpdateTag UpdateTag 更新标签
	UpdateTag(ctx context.Context, req *UpdateTagRequest, opts ...http.CallOption) (rsp *UpdateTagReply, err error)
}

type TagHTTPClientImpl struct {
	cc *http.Client
}

func NewTagHTTPClient(client *http.Client) TagHTTPClient {
	return &TagHTTPClientImpl{client}
}

// CreateTag CreateTag 创建标签
func (c *TagHTTPClientImpl) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...http.CallOption) (*CreateTagReply, error) {
	var out CreateTagReply
	pattern := "/v1/tags"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTagCreateTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteTag DeleteTag 删除标签
func (c *TagHTTPClientImpl) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...http.CallOption) (*DeleteTagReply, error) {
	var out DeleteTagReply
	pattern := "/v1/tags/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTagDeleteTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTag GetTag 获取标签详情
func (c *TagHTTPClientImpl) GetTag(ctx context.Context, in *GetTagRequest, opts ...http.CallOption) (*GetTagReply, error) {
	var out GetTagReply
	pattern := "/v1/tags/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTagGetTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTags ListTags 列出标签，输入分页参数，返回标签列表
func (c *TagHTTPClientImpl) ListTags(ctx context.Context, in *ListTagsRequest, opts ...http.CallOption) (*ListTagsReply, error) {
	var out ListTagsReply
	pattern := "/v1/tags"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTagListTags))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTag UpdateTag 更新标签
func (c *TagHTTPClientImpl) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...http.CallOption) (*UpdateTagReply, error) {
	var out UpdateTagReply
	pattern := "/v1/tags/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTagUpdateTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
