server:
  http:
    addr: 0.0.0.0:8003
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 1s
data:
  meilisearch:
    endpoint: http://127.0.0.1:7700
    api_key: "7Sf1EppCBY8W43wlBxBltDErjVyc4Wfb0g3EFBr9mws"
    index_name: posts
  clients:
    post_endpoint: 127.0.0.1:9001
    timeout: 1s
