server:
  http:
    addr: 0.0.0.0:8003
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 1s
data:
  meilisearch:
    endpoint: http://meilisearch:7700
    api_key: "BCSk29xyDFe0-Oa5g0SrqJWfAFbeRK36LVymcHin_fg"
    index_name: posts
  clients:
    post_endpoint: discovery:///post.service
    timeout: 1s
registry:
  etcd:
    endpoints:
      - "etcd:2379"
    timeout: 5s