server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:GP123@tcp(mariadb:3306)/gopalette?parseTime=True&loc=Local
  redis:
    addr: redis:6379
    password: "GP123"
    read_timeout: 0.2s
    write_timeout: 0.2s
  clients:
    user_endpoint: discovery:///user.service
    search_endpoint: discovery:///search.service
    timeout: 1s
registry:
  etcd:
    endpoints:
      - "etcd:2379"
    timeout: 5s
auth:
  jwt_access_secret: "GPA"
  jwt_refresh_secret: "GPR"
  jwt_access_expire: 900s
  jwt_refresh_expire: 604800s
  issuer: "GoPalette"