server:
  http:
    addr: 0.0.0.0:8001
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 30s
data:
  database:
    driver: mysql
    source: root:${MYSQL_ROOT_PASSWORD:GP123}@tcp(${MYSQL_HOST:mariadb}:${MYSQL_PORT:3306})/${MYSQL_DATABASE:gopalette_post}?parseTime=True&loc=Local
  redis:
    addr: ${REDIS_ADDR:redis:6379}
    password: "${REDIS_PASSWORD:GP123}"
    db: 2
    dial_timeout: 0.2s
    read_timeout: 0.2s
    write_timeout: 0.2s
  event_redis:
    addr: ${REDIS_ADDR:redis:6379}
    password: "${REDIS_PASSWORD:GP123}"
    db: 0
    dial_timeout: 0.2s
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  etcd:
    endpoints:
      - "${ETCD_ENDPOINT:etcd:2379}"
    timeout: 5s
auth: {}
