server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:GP123@tcp(mariadb:3306)/gopalette?parseTime=True&loc=Local
  redis:
    addr: redis:6379
    password: "GP123"
    db: 0
    dial_timeout: 0.2s
    read_timeout: 0.2s
    write_timeout: 0.2s
  clients:
    post_endpoint: discovery:///post.service
    user_endpoint: discovery:///user.service
    timeout: 1s
registry:
  etcd:
    endpoints:
      - "etcd:2379"
    timeout: 5s
auth:
  jwt_access_secret: "GPA"
