// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Create(context1 context.Context, user *User) (*User, error) {
	ret := _mock.Called(context1, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *User) (*User, error)); ok {
		return returnFunc(context1, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *User) *User); ok {
		r0 = returnFunc(context1, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *User) error); ok {
		r1 = returnFunc(context1, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - user *User
func (_e *MockUserRepo_Expecter) Create(context1 interface{}, user interface{}) *MockUserRepo_Create_Call {
	return &MockUserRepo_Create_Call{Call: _e.mock.On("Create", context1, user)}
}

func (_c *MockUserRepo_Create_Call) Run(run func(context1 context.Context, user *User)) *MockUserRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *User
		if args[1] != nil {
			arg1 = args[1].(*User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_Create_Call) Return(user1 *User, err error) *MockUserRepo_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepo_Create_Call) RunAndReturn(run func(context1 context.Context, user *User) (*User, error)) *MockUserRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Delete(context1 context.Context, n int64) error {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(context1, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - n int64
func (_e *MockUserRepo_Expecter) Delete(context1 interface{}, n interface{}) *MockUserRepo_Delete_Call {
	return &MockUserRepo_Delete_Call{Call: _e.mock.On("Delete", context1, n)}
}

func (_c *MockUserRepo_Delete_Call) Run(run func(context1 context.Context, n int64)) *MockUserRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_Delete_Call) Return(err error) *MockUserRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_Delete_Call) RunAndReturn(run func(context1 context.Context, n int64) error) *MockUserRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) FindByEmail(context1 context.Context, s string) (*User, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepo_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockUserRepo_Expecter) FindByEmail(context1 interface{}, s interface{}) *MockUserRepo_FindByEmail_Call {
	return &MockUserRepo_FindByEmail_Call{Call: _e.mock.On("FindByEmail", context1, s)}
}

func (_c *MockUserRepo_FindByEmail_Call) Run(run func(context1 context.Context, s string)) *MockUserRepo_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_FindByEmail_Call) Return(user *User, err error) *MockUserRepo_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_FindByEmail_Call) RunAndReturn(run func(context1 context.Context, s string) (*User, error)) *MockUserRepo_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Get(context1 context.Context, n int64) (*User, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*User, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *User); ok {
		r0 = returnFunc(context1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - n int64
func (_e *MockUserRepo_Expecter) Get(context1 interface{}, n interface{}) *MockUserRepo_Get_Call {
	return &MockUserRepo_Get_Call{Call: _e.mock.On("Get", context1, n)}
}

func (_c *MockUserRepo_Get_Call) Run(run func(context1 context.Context, n int64)) *MockUserRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_Get_Call) Return(user *User, err error) *MockUserRepo_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_Get_Call) RunAndReturn(run func(context1 context.Context, n int64) (*User, error)) *MockUserRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) List(ctx context.Context, page int64, pageSize int64) ([]*User, int64, error) {
	ret := _mock.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*User
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) ([]*User, int64, error)); ok {
		return returnFunc(ctx, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) []*User); ok {
		r0 = returnFunc(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) int64); ok {
		r1 = returnFunc(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, int64) error); ok {
		r2 = returnFunc(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - pageSize int64
func (_e *MockUserRepo_Expecter) List(ctx interface{}, page interface{}, pageSize interface{}) *MockUserRepo_List_Call {
	return &MockUserRepo_List_Call{Call: _e.mock.On("List", ctx, page, pageSize)}
}

func (_c *MockUserRepo_List_Call) Run(run func(ctx context.Context, page int64, pageSize int64)) *MockUserRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_List_Call) Return(users []*User, n int64, err error) *MockUserRepo_List_Call {
	_c.Call.Return(users, n, err)
	return _c
}

func (_c *MockUserRepo_List_Call) RunAndReturn(run func(ctx context.Context, page int64, pageSize int64) ([]*User, int64, error)) *MockUserRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Update(context1 context.Context, user *User, strings []string) (*User, error) {
	ret := _mock.Called(context1, user, strings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *User, []string) (*User, error)); ok {
		return returnFunc(context1, user, strings)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *User, []string) *User); ok {
		r0 = returnFunc(context1, user, strings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *User, []string) error); ok {
		r1 = returnFunc(context1, user, strings)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - user *User
//   - strings []string
func (_e *MockUserRepo_Expecter) Update(context1 interface{}, user interface{}, strings interface{}) *MockUserRepo_Update_Call {
	return &MockUserRepo_Update_Call{Call: _e.mock.On("Update", context1, user, strings)}
}

func (_c *MockUserRepo_Update_Call) Run(run func(context1 context.Context, user *User, strings []string)) *MockUserRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *User
		if args[1] != nil {
			arg1 = args[1].(*User)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_Update_Call) Return(user1 *User, err error) *MockUserRepo_Update_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepo_Update_Call) RunAndReturn(run func(context1 context.Context, user *User, strings []string) (*User, error)) *MockUserRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}
