// Code generated by Wire. DO NOT EDIT.

//go:generate go tool wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/satiu123/GoPalette/app/post/service/internal/biz"
	"github.com/satiu123/GoPalette/app/post/service/internal/conf"
	"github.com/satiu123/GoPalette/app/post/service/internal/data"
	"github.com/satiu123/GoPalette/app/post/service/internal/server"
	"github.com/satiu123/GoPalette/app/post/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	client, err := NewEtcdClient(registry)
	if err != nil {
		return nil, nil, err
	}
	etcdRegistry := NewRegistry(client)
	userClient := data.NewUserClient(etcdRegistry, confData)
	searchClient := data.NewSearchClient(etcdRegistry, confData)
	dataData, cleanup, err := data.NewData(confData, logger, userClient, searchClient)
	if err != nil {
		return nil, nil, err
	}
	postRepo := data.NewPostRepo(dataData, logger)
	postUsecase := biz.NewPostUsecase(postRepo, logger)
	postService := service.NewPostService(postUsecase, userClient, searchClient, logger)
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	categoryUsecase := biz.NewCategoryUsecase(categoryRepo, logger)
	categoryService := service.NewCategoryService(categoryUsecase, logger)
	tagRepo := data.NewTagRepo(dataData, logger)
	tagUsecase := biz.NewTagUsecase(tagRepo, logger)
	tagService := service.NewTagService(tagUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, auth, postService, categoryService, tagService, logger)
	httpServer := server.NewHTTPServer(confServer, auth, postService, categoryService, tagService, logger)
	app := newApp(logger, grpcServer, httpServer, etcdRegistry)
	return app, func() {
		cleanup()
	}, nil
}
