const gatewayBase = process.env.GATEWAY_BASE || 'http://127.0.0.1:8080'
const now = Date.now()

const username = process.env.E2E_USERNAME || `e2e_user_${now}`
const email = process.env.E2E_EMAIL || `e2e_${now}@example.com`
const password = process.env.E2E_PASSWORD || 'E2EPass123!'

type AnyObject = Record<string, unknown>

function decodeJwtPayload(token: string): AnyObject {
  const payload = token.split('.')[1]
  if (!payload) return {}

  const normalized = payload.replace(/-/g, '+').replace(/_/g, '/')
  const padded = normalized.padEnd(Math.ceil(normalized.length / 4) * 4, '=')
  const json = Buffer.from(padded, 'base64').toString('utf8')

  return JSON.parse(json) as AnyObject
}

function pickUserId(token: string) {
  const payload = decodeJwtPayload(token)
  const candidate = payload.userId || payload.user_id || payload.sub || payload.id
  if (typeof candidate === 'string') return candidate
  if (typeof candidate === 'number' && Number.isFinite(candidate)) return String(candidate)
  return ''
}

async function ensureCategoryId(accessToken: string) {
  const list = await callApi<{ categories?: Array<{ id?: string }> }>(
    '/v1/categories?page=1&pageSize=50',
    {
      method: 'GET',
      headers: {
        authorization: `Bearer ${accessToken}`
      }
    }
  )

  const first = list.categories?.[0]
  if (first?.id) return first.id

  const created = await callApi<{ category?: { id?: string } }>('/v1/categories', {
    method: 'POST',
    headers: {
      authorization: `Bearer ${accessToken}`
    },
    body: JSON.stringify({
      name: `E2E Category ${now}`,
      slug: `e2e-category-${now}`,
      description: 'auto-generated by e2e smoke script'
    })
  })

  const categoryId = created.category?.id
  if (!categoryId) {
    throw new Error('cannot resolve categoryId')
  }

  return categoryId
}

async function callApi<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${gatewayBase}${path}`, {
    ...init,
    headers: {
      'content-type': 'application/json',
      ...(init?.headers || {})
    }
  })

  const text = await response.text()
  const data = text ? JSON.parse(text) : {}

  if (!response.ok) {
    throw new Error(`${response.status} ${response.statusText}: ${JSON.stringify(data)}`)
  }

  return data as T
}

async function main() {
  console.log(`gateway: ${gatewayBase}`)

  try {
    await callApi('/v1/users/register', {
      method: 'POST',
      body: JSON.stringify({ username, email, password })
    })
    console.log('register: ok')
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    if (message.includes('already') || message.includes('exists') || message.includes('409')) {
      console.log('register: already exists, continue')
    } else {
      throw error
    }
  }

  const login = await callApi<{ accessToken?: string, refreshToken?: string }>('/v1/users/login', {
    method: 'POST',
    body: JSON.stringify({ email, password })
  })

  if (!login.accessToken || !login.refreshToken) {
    throw new Error('login response missing token')
  }
  console.log('login: ok')

  const userId = pickUserId(login.accessToken)
  if (!userId) {
    throw new Error('cannot parse userId from accessToken')
  }

  const authHeader = { authorization: `Bearer ${login.accessToken}` }

  const profile = await callApi<{ user?: AnyObject }>(`/v1/users/${userId}`, {
    method: 'GET',
    headers: authHeader
  })
  if (!profile.user) {
    throw new Error('get profile returned empty user')
  }
  console.log('profile:get: ok')

  const updatedName = `e2e_updated_${now}`
  const updated = await callApi<{ user?: AnyObject }>(`/v1/users/${userId}?updateMask=username,email,avatarURL`, {
    method: 'PATCH',
    headers: authHeader,
    body: JSON.stringify({
      id: userId,
      username: updatedName,
      email,
      avatarURL: `https://picsum.photos/seed/${now}/120/120`
    })
  })
  if (!updated.user) {
    throw new Error('update profile returned empty user')
  }
  console.log('profile:patch: ok')

  const categoryId = await ensureCategoryId(login.accessToken)
  console.log('category: ok')

  const slug = `e2e-smoke-post-${now}`
  const createPost = await callApi<{ post?: AnyObject }>('/v1/posts', {
    method: 'POST',
    headers: authHeader,
    body: JSON.stringify({
      title: 'E2E Smoke Post',
      summary: 'Created by smoke test',
      slug,
      content: '# E2E Smoke\n\nThis post is generated by smoke script.',
      status: 'PUBLISHED',
      categoryId,
      tags: ['e2e', 'smoke']
    })
  })
  if (!createPost.post) {
    throw new Error('create post returned empty post')
  }
  console.log('post:create: ok')

  const listed = await callApi<{ posts?: Array<{ slug?: string }> }>(`/v1/posts?page=1&pageSize=50`)
  const foundInList = Boolean(listed.posts?.some(post => post.slug === slug))
  if (!foundInList) {
    throw new Error('created post not found in list')
  }
  console.log('post:list: ok')

  const bySlug = await callApi<{ post?: AnyObject }>(`/v1/posts/slug/${slug}`)
  if (!bySlug.post) {
    throw new Error('get by slug returned empty post')
  }
  console.log('post:getBySlug: ok')

  console.log('\nsmoke test passed')
  console.log(`userId=${userId}`)
  console.log(`slug=${slug}`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
