const gatewayBase = process.env.GATEWAY_BASE || 'http://127.0.0.1:8080'
const count = Number(process.env.SEED_COUNT || '6')
const now = Date.now()

const username = process.env.SEED_USERNAME || `seed_user_${now}`
const email = process.env.SEED_EMAIL || `seed_${now}@example.com`
const password = process.env.SEED_PASSWORD || 'SeedPass123!'

type LoginReply = {
  accessToken?: string
  refreshToken?: string
}

type CategoryListReply = {
  categories?: Array<{ id?: string, name?: string }>
}

type PostReply = {
  post?: {
    id?: string
    slug?: string
    title?: string
  }
}

async function callApi<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${gatewayBase}${path}`, {
    ...init,
    headers: {
      'content-type': 'application/json',
      ...(init?.headers || {})
    }
  })

  const text = await response.text()
  const data = text ? JSON.parse(text) : {}

  if (!response.ok) {
    throw new Error(`${response.status} ${response.statusText}: ${JSON.stringify(data)}`)
  }

  return data as T
}

async function ensureUser() {
  try {
    await callApi('/v1/users/register', {
      method: 'POST',
      body: JSON.stringify({ username, email, password })
    })
    console.log(`registered: ${email}`)
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    if (message.includes('already') || message.includes('exists') || message.includes('409')) {
      console.log(`register skipped: ${email}`)
      return
    }
    throw error
  }
}

async function login() {
  const loginReply = await callApi<LoginReply>('/v1/users/login', {
    method: 'POST',
    body: JSON.stringify({ email, password })
  })

  if (!loginReply.accessToken) {
    throw new Error('login did not return accessToken')
  }

  console.log(`login ok: ${email}`)
  return loginReply.accessToken
}

async function ensureCategoryId(accessToken: string) {
  const list = await callApi<CategoryListReply>('/v1/categories?page=1&pageSize=50', {
    method: 'GET',
    headers: {
      authorization: `Bearer ${accessToken}`
    }
  })

  const first = list.categories?.[0]
  if (first?.id) {
    return first.id
  }

  const slug = `seed-category-${now}`
  const created = await callApi<{ category?: { id?: string } }>('/v1/categories', {
    method: 'POST',
    headers: {
      authorization: `Bearer ${accessToken}`
    },
    body: JSON.stringify({
      name: `Seed Category ${now}`,
      slug,
      description: 'auto-generated by seed script'
    })
  })

  const categoryId = created.category?.id
  if (!categoryId) {
    throw new Error('cannot resolve categoryId for post creation')
  }

  return categoryId
}

async function createPosts(accessToken: string, categoryId: string) {
  const created: Array<{ id: string, slug: string, title: string }> = []

  for (let i = 1; i <= count; i += 1) {
    const slug = `seed-post-${now}-${i}`
    const title = `Seed Post ${i}`

    const payload = {
      title,
      summary: `Auto-generated seed summary ${i}`,
      slug,
      content: `# ${title}\n\nGenerated at ${new Date().toISOString()}.`,
      status: 'PUBLISHED',
      categoryId,
      tags: ['seed', 'smoke', `batch-${now}`]
    }

    const reply = await callApi<PostReply>('/v1/posts', {
      method: 'POST',
      headers: {
        authorization: `Bearer ${accessToken}`
      },
      body: JSON.stringify(payload)
    })

    created.push({
      id: String(reply.post?.id || ''),
      slug: String(reply.post?.slug || slug),
      title: String(reply.post?.title || title)
    })

    console.log(`created ${i}/${count}: ${slug}`)
  }

  return created
}

async function main() {
  console.log(`gateway: ${gatewayBase}`)
  await ensureUser()
  const token = await login()
  const categoryId = await ensureCategoryId(token)
  console.log(`category ok: ${categoryId}`)
  const created = await createPosts(token, categoryId)

  console.log('\nseed result:')
  for (const item of created) {
    console.log(`- ${item.slug} (id=${item.id || 'n/a'})`)
  }
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
