// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsPostNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_POST_NOT_FOUND.String() && e.Code == 404
}

func ErrorPostNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_POST_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsCommentNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_COMMENT_NOT_FOUND.String() && e.Code == 404
}

func ErrorCommentNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_COMMENT_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsParentNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PARENT_NOT_FOUND.String() && e.Code == 400
}

func ErrorParentNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_PARENT_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsInvalidArgument(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_ARGUMENT.String() && e.Code == 400
}

func ErrorInvalidArgument(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_ARGUMENT.String(), fmt.Sprintf(format, args...))
}

func IsUnauthenticated(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNAUTHENTICATED.String() && e.Code == 401
}

func ErrorUnauthenticated(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_UNAUTHENTICATED.String(), fmt.Sprintf(format, args...))
}

func IsAccessDenied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ACCESS_DENIED.String() && e.Code == 403
}

func ErrorAccessDenied(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_ACCESS_DENIED.String(), fmt.Sprintf(format, args...))
}

func IsRateLimited(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RATE_LIMITED.String() && e.Code == 429
}

func ErrorRateLimited(format string, args ...interface{}) *errors.Error {
	return errors.New(429, ErrorReason_RATE_LIMITED.String(), fmt.Sprintf(format, args...))
}
