// Code generated by Wire. DO NOT EDIT.

//go:generate go tool wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/satiu123/GoPalette/app/user/service/internal/biz"
	"github.com/satiu123/GoPalette/app/user/service/internal/conf"
	"github.com/satiu123/GoPalette/app/user/service/internal/data"
	"github.com/satiu123/GoPalette/app/user/service/internal/health"
	"github.com/satiu123/GoPalette/app/user/service/internal/server"
	"github.com/satiu123/GoPalette/app/user/service/internal/service"
	"github.com/satiu123/GoPalette/pkg/opentelemetry"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, registry *conf.Registry, logger log.Logger, serviceName opentelemetry.ServiceName) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	authSessionRepo := data.NewAuthSessionRepo(dataData)
	authUsecase := biz.NewAuthUsecase(auth, userRepo, authSessionRepo, logger)
	userService := service.NewUserService(userUsecase, authUsecase, logger)
	mySQLChecker := health.NewMySQLCheckerWrapper(dataData)
	redisChecker := health.NewRedisCheckerWrapper(dataData)
	healthHealth := health.NewHealthWrapper(mySQLChecker, redisChecker)
	int64Counter := opentelemetry.NewRequestCounter(serviceName)
	float64Histogram := opentelemetry.NewSecondsHistogram(serviceName)
	grpcServer := server.NewGRPCServer(confServer, auth, userService, logger, healthHealth, int64Counter, float64Histogram)
	httpServer := server.NewHTTPServer(confServer, auth, userService, logger, healthHealth, int64Counter, float64Histogram)
	client, err := NewEtcdClient(registry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	etcdRegistry := NewRegistry(client)
	app := newApp(logger, grpcServer, httpServer, etcdRegistry)
	return app, func() {
		cleanup()
	}, nil
}
