// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsInvalidArgument(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_ARGUMENT.String() && e.Code == 400
}

func ErrorInvalidArgument(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_ARGUMENT.String(), fmt.Sprintf(format, args...))
}

func IsIndexSyncFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INDEX_SYNC_FAILED.String() && e.Code == 500
}

func ErrorIndexSyncFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INDEX_SYNC_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsSearchFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SEARCH_FAILED.String() && e.Code == 500
}

func ErrorSearchFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_SEARCH_FAILED.String(), fmt.Sprintf(format, args...))
}
