// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: search/v1/search.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSearchGetRebuildStatus = "/api.search.v1.Search/GetRebuildStatus"
const OperationSearchRebuildIndex = "/api.search.v1.Search/RebuildIndex"
const OperationSearchSearchPosts = "/api.search.v1.Search/SearchPosts"

type SearchHTTPServer interface {
	// GetRebuildStatus 查询异步重建任务状态，不传 task_id 返回最近一次任务状态
	GetRebuildStatus(context.Context, *GetRebuildStatusRequest) (*GetRebuildStatusReply, error)
	// RebuildIndex 管理员触发：从 Post Service 拉取全量并重建索引
	RebuildIndex(context.Context, *RebuildIndexRequest) (*RebuildIndexReply, error)
	// SearchPosts 对外搜索接口
	SearchPosts(context.Context, *SearchPostsRequest) (*SearchPostsReply, error)
}

func RegisterSearchHTTPServer(s *http.Server, srv SearchHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/search/posts", _Search_SearchPosts0_HTTP_Handler(srv))
	r.POST("/v1/search/rebuild", _Search_RebuildIndex0_HTTP_Handler(srv))
	r.GET("/v1/search/rebuild/{task_id}", _Search_GetRebuildStatus0_HTTP_Handler(srv))
	r.GET("/v1/search/rebuild/status", _Search_GetRebuildStatus1_HTTP_Handler(srv))
}

func _Search_SearchPosts0_HTTP_Handler(srv SearchHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchPostsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchSearchPosts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchPosts(ctx, req.(*SearchPostsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchPostsReply)
		return ctx.Result(200, reply)
	}
}

func _Search_RebuildIndex0_HTTP_Handler(srv SearchHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RebuildIndexRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchRebuildIndex)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RebuildIndex(ctx, req.(*RebuildIndexRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RebuildIndexReply)
		return ctx.Result(200, reply)
	}
}

func _Search_GetRebuildStatus0_HTTP_Handler(srv SearchHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRebuildStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchGetRebuildStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRebuildStatus(ctx, req.(*GetRebuildStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRebuildStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Search_GetRebuildStatus1_HTTP_Handler(srv SearchHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRebuildStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchGetRebuildStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRebuildStatus(ctx, req.(*GetRebuildStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRebuildStatusReply)
		return ctx.Result(200, reply)
	}
}

type SearchHTTPClient interface {
	// GetRebuildStatus 查询异步重建任务状态，不传 task_id 返回最近一次任务状态
	GetRebuildStatus(ctx context.Context, req *GetRebuildStatusRequest, opts ...http.CallOption) (rsp *GetRebuildStatusReply, err error)
	// RebuildIndex 管理员触发：从 Post Service 拉取全量并重建索引
	RebuildIndex(ctx context.Context, req *RebuildIndexRequest, opts ...http.CallOption) (rsp *RebuildIndexReply, err error)
	// SearchPosts 对外搜索接口
	SearchPosts(ctx context.Context, req *SearchPostsRequest, opts ...http.CallOption) (rsp *SearchPostsReply, err error)
}

type SearchHTTPClientImpl struct {
	cc *http.Client
}

func NewSearchHTTPClient(client *http.Client) SearchHTTPClient {
	return &SearchHTTPClientImpl{client}
}

// GetRebuildStatus 查询异步重建任务状态，不传 task_id 返回最近一次任务状态
func (c *SearchHTTPClientImpl) GetRebuildStatus(ctx context.Context, in *GetRebuildStatusRequest, opts ...http.CallOption) (*GetRebuildStatusReply, error) {
	var out GetRebuildStatusReply
	pattern := "/v1/search/rebuild/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchGetRebuildStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RebuildIndex 管理员触发：从 Post Service 拉取全量并重建索引
func (c *SearchHTTPClientImpl) RebuildIndex(ctx context.Context, in *RebuildIndexRequest, opts ...http.CallOption) (*RebuildIndexReply, error) {
	var out RebuildIndexReply
	pattern := "/v1/search/rebuild"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSearchRebuildIndex))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchPosts 对外搜索接口
func (c *SearchHTTPClientImpl) SearchPosts(ctx context.Context, in *SearchPostsRequest, opts ...http.CallOption) (*SearchPostsReply, error) {
	var out SearchPostsReply
	pattern := "/v1/search/posts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchSearchPosts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
