// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: search/v1/search.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostsRequest) Reset() {
	*x = SearchPostsRequest{}
	mi := &file_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostsRequest) ProtoMessage() {}

func (x *SearchPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostsRequest.ProtoReflect.Descriptor instead.
func (*SearchPostsRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchPostsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchPostsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchPostsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchPostsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type PostSearchInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	CategoryName  string                 `protobuf:"bytes,5,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostSearchInfo) Reset() {
	*x = PostSearchInfo{}
	mi := &file_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostSearchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSearchInfo) ProtoMessage() {}

func (x *PostSearchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSearchInfo.ProtoReflect.Descriptor instead.
func (*PostSearchInfo) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *PostSearchInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostSearchInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostSearchInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PostSearchInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PostSearchInfo) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *PostSearchInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PostSearchInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SearchPostsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PostSearchInfo      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int64                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostsReply) Reset() {
	*x = SearchPostsReply{}
	mi := &file_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostsReply) ProtoMessage() {}

func (x *SearchPostsReply) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostsReply.ProtoReflect.Descriptor instead.
func (*SearchPostsReply) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchPostsReply) GetResults() []*PostSearchInfo {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchPostsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchPostsReply) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type SyncPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Slug          string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	CategoryName  string                 `protobuf:"bytes,6,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPostRequest) Reset() {
	*x = SyncPostRequest{}
	mi := &file_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPostRequest) ProtoMessage() {}

func (x *SyncPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPostRequest.ProtoReflect.Descriptor instead.
func (*SyncPostRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SyncPostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SyncPostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SyncPostRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SyncPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SyncPostRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SyncPostRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *SyncPostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SyncPostRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SyncPostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPostReply) Reset() {
	*x = SyncPostReply{}
	mi := &file_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPostReply) ProtoMessage() {}

func (x *SyncPostReply) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPostReply.ProtoReflect.Descriptor instead.
func (*SyncPostReply) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *SyncPostReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIndexRequest) Reset() {
	*x = DeleteIndexRequest{}
	mi := &file_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexRequest) ProtoMessage() {}

func (x *DeleteIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexRequest.ProtoReflect.Descriptor instead.
func (*DeleteIndexRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteIndexRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type DeleteIndexReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIndexReply) Reset() {
	*x = DeleteIndexReply{}
	mi := &file_search_v1_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexReply) ProtoMessage() {}

func (x *DeleteIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexReply.ProtoReflect.Descriptor instead.
func (*DeleteIndexReply) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteIndexReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RebuildIndexRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResetFirst          bool                   `protobuf:"varint,1,opt,name=reset_first,json=resetFirst,proto3" json:"reset_first,omitempty"`
	IncludeNonPublished bool                   `protobuf:"varint,2,opt,name=include_non_published,json=includeNonPublished,proto3" json:"include_non_published,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RebuildIndexRequest) Reset() {
	*x = RebuildIndexRequest{}
	mi := &file_search_v1_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildIndexRequest) ProtoMessage() {}

func (x *RebuildIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildIndexRequest.ProtoReflect.Descriptor instead.
func (*RebuildIndexRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{7}
}

func (x *RebuildIndexRequest) GetResetFirst() bool {
	if x != nil {
		return x.ResetFirst
	}
	return false
}

func (x *RebuildIndexRequest) GetIncludeNonPublished() bool {
	if x != nil {
		return x.IncludeNonPublished
	}
	return false
}

type RebuildIndexReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Task          *RebuildTaskInfo       `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildIndexReply) Reset() {
	*x = RebuildIndexReply{}
	mi := &file_search_v1_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildIndexReply) ProtoMessage() {}

func (x *RebuildIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildIndexReply.ProtoReflect.Descriptor instead.
func (*RebuildIndexReply) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{8}
}

func (x *RebuildIndexReply) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RebuildIndexReply) GetTask() *RebuildTaskInfo {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetRebuildStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRebuildStatusRequest) Reset() {
	*x = GetRebuildStatusRequest{}
	mi := &file_search_v1_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRebuildStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRebuildStatusRequest) ProtoMessage() {}

func (x *GetRebuildStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRebuildStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRebuildStatusRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{9}
}

func (x *GetRebuildStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetRebuildStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *RebuildTaskInfo       `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRebuildStatusReply) Reset() {
	*x = GetRebuildStatusReply{}
	mi := &file_search_v1_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRebuildStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRebuildStatusReply) ProtoMessage() {}

func (x *GetRebuildStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRebuildStatusReply.ProtoReflect.Descriptor instead.
func (*GetRebuildStatusReply) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{10}
}

func (x *GetRebuildStatusReply) GetTask() *RebuildTaskInfo {
	if x != nil {
		return x.Task
	}
	return nil
}

type RebuildTaskInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TaskId              string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ResetFirst          bool                   `protobuf:"varint,3,opt,name=reset_first,json=resetFirst,proto3" json:"reset_first,omitempty"`
	IncludeNonPublished bool                   `protobuf:"varint,4,opt,name=include_non_published,json=includeNonPublished,proto3" json:"include_non_published,omitempty"`
	IndexedCount        int64                  `protobuf:"varint,5,opt,name=indexed_count,json=indexedCount,proto3" json:"indexed_count,omitempty"`
	Total               int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RebuildTaskInfo) Reset() {
	*x = RebuildTaskInfo{}
	mi := &file_search_v1_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildTaskInfo) ProtoMessage() {}

func (x *RebuildTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildTaskInfo.ProtoReflect.Descriptor instead.
func (*RebuildTaskInfo) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{11}
}

func (x *RebuildTaskInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RebuildTaskInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RebuildTaskInfo) GetResetFirst() bool {
	if x != nil {
		return x.ResetFirst
	}
	return false
}

func (x *RebuildTaskInfo) GetIncludeNonPublished() bool {
	if x != nil {
		return x.IncludeNonPublished
	}
	return false
}

func (x *RebuildTaskInfo) GetIndexedCount() int64 {
	if x != nil {
		return x.IndexedCount
	}
	return 0
}

func (x *RebuildTaskInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RebuildTaskInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RebuildTaskInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RebuildTaskInfo) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

var File_search_v1_search_proto protoreflect.FileDescriptor

const file_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x16search/v1/search.proto\x12\rapi.search.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\x12SearchPostsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\xd8\x01\n" +
	"\x0ePostSearchInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12#\n" +
	"\rcategory_name\x18\x05 \x01(\tR\fcategoryName\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x82\x01\n" +
	"\x10SearchPostsReply\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.api.search.v1.PostSearchInfoR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x03R\n" +
	"totalPages\"\xf3\x01\n" +
	"\x0fSyncPostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12#\n" +
	"\rcategory_name\x18\x06 \x01(\tR\fcategoryName\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\")\n" +
	"\rSyncPostReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x12DeleteIndexRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\",\n" +
	"\x10DeleteIndexReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"j\n" +
	"\x13RebuildIndexRequest\x12\x1f\n" +
	"\vreset_first\x18\x01 \x01(\bR\n" +
	"resetFirst\x122\n" +
	"\x15include_non_published\x18\x02 \x01(\bR\x13includeNonPublished\"c\n" +
	"\x11RebuildIndexReply\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x122\n" +
	"\x04task\x18\x02 \x01(\v2\x1e.api.search.v1.RebuildTaskInfoR\x04task\"2\n" +
	"\x17GetRebuildStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"K\n" +
	"\x15GetRebuildStatusReply\x122\n" +
	"\x04task\x18\x01 \x01(\v2\x1e.api.search.v1.RebuildTaskInfoR\x04task\"\xef\x02\n" +
	"\x0fRebuildTaskInfo\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vreset_first\x18\x03 \x01(\bR\n" +
	"resetFirst\x122\n" +
	"\x15include_non_published\x18\x04 \x01(\bR\x13includeNonPublished\x12#\n" +
	"\rindexed_count\x18\x05 \x01(\x03R\findexedCount\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x03R\x05total\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt2\xad\x04\n" +
	"\x06Search\x12k\n" +
	"\vSearchPosts\x12!.api.search.v1.SearchPostsRequest\x1a\x1f.api.search.v1.SearchPostsReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/search/posts\x12H\n" +
	"\bSyncPost\x12\x1e.api.search.v1.SyncPostRequest\x1a\x1c.api.search.v1.SyncPostReply\x12Q\n" +
	"\vDeleteIndex\x12!.api.search.v1.DeleteIndexRequest\x1a\x1f.api.search.v1.DeleteIndexReply\x12s\n" +
	"\fRebuildIndex\x12\".api.search.v1.RebuildIndexRequest\x1a .api.search.v1.RebuildIndexReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/search/rebuild\x12\xa3\x01\n" +
	"\x10GetRebuildStatus\x12&.api.search.v1.GetRebuildStatusRequest\x1a$.api.search.v1.GetRebuildStatusReply\"A\x82\xd3\xe4\x93\x02;Z\x1e\x12\x1c/v1/search/rebuild/{task_id}\x12\x19/v1/search/rebuild/statusBA\n" +
	"\rapi.search.v1P\x01Z.github.com/satiu123/GoPalette/api/search/v1;v1b\x06proto3"

var (
	file_search_v1_search_proto_rawDescOnce sync.Once
	file_search_v1_search_proto_rawDescData []byte
)

func file_search_v1_search_proto_rawDescGZIP() []byte {
	file_search_v1_search_proto_rawDescOnce.Do(func() {
		file_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)))
	})
	return file_search_v1_search_proto_rawDescData
}

var file_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_search_v1_search_proto_goTypes = []any{
	(*SearchPostsRequest)(nil),      // 0: api.search.v1.SearchPostsRequest
	(*PostSearchInfo)(nil),          // 1: api.search.v1.PostSearchInfo
	(*SearchPostsReply)(nil),        // 2: api.search.v1.SearchPostsReply
	(*SyncPostRequest)(nil),         // 3: api.search.v1.SyncPostRequest
	(*SyncPostReply)(nil),           // 4: api.search.v1.SyncPostReply
	(*DeleteIndexRequest)(nil),      // 5: api.search.v1.DeleteIndexRequest
	(*DeleteIndexReply)(nil),        // 6: api.search.v1.DeleteIndexReply
	(*RebuildIndexRequest)(nil),     // 7: api.search.v1.RebuildIndexRequest
	(*RebuildIndexReply)(nil),       // 8: api.search.v1.RebuildIndexReply
	(*GetRebuildStatusRequest)(nil), // 9: api.search.v1.GetRebuildStatusRequest
	(*GetRebuildStatusReply)(nil),   // 10: api.search.v1.GetRebuildStatusReply
	(*RebuildTaskInfo)(nil),         // 11: api.search.v1.RebuildTaskInfo
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_search_v1_search_proto_depIdxs = []int32{
	12, // 0: api.search.v1.PostSearchInfo.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: api.search.v1.SearchPostsReply.results:type_name -> api.search.v1.PostSearchInfo
	12, // 2: api.search.v1.SyncPostRequest.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: api.search.v1.RebuildIndexReply.task:type_name -> api.search.v1.RebuildTaskInfo
	11, // 4: api.search.v1.GetRebuildStatusReply.task:type_name -> api.search.v1.RebuildTaskInfo
	12, // 5: api.search.v1.RebuildTaskInfo.started_at:type_name -> google.protobuf.Timestamp
	12, // 6: api.search.v1.RebuildTaskInfo.finished_at:type_name -> google.protobuf.Timestamp
	0,  // 7: api.search.v1.Search.SearchPosts:input_type -> api.search.v1.SearchPostsRequest
	3,  // 8: api.search.v1.Search.SyncPost:input_type -> api.search.v1.SyncPostRequest
	5,  // 9: api.search.v1.Search.DeleteIndex:input_type -> api.search.v1.DeleteIndexRequest
	7,  // 10: api.search.v1.Search.RebuildIndex:input_type -> api.search.v1.RebuildIndexRequest
	9,  // 11: api.search.v1.Search.GetRebuildStatus:input_type -> api.search.v1.GetRebuildStatusRequest
	2,  // 12: api.search.v1.Search.SearchPosts:output_type -> api.search.v1.SearchPostsReply
	4,  // 13: api.search.v1.Search.SyncPost:output_type -> api.search.v1.SyncPostReply
	6,  // 14: api.search.v1.Search.DeleteIndex:output_type -> api.search.v1.DeleteIndexReply
	8,  // 15: api.search.v1.Search.RebuildIndex:output_type -> api.search.v1.RebuildIndexReply
	10, // 16: api.search.v1.Search.GetRebuildStatus:output_type -> api.search.v1.GetRebuildStatusReply
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_search_v1_search_proto_init() }
func file_search_v1_search_proto_init() {
	if File_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_v1_search_proto_goTypes,
		DependencyIndexes: file_search_v1_search_proto_depIdxs,
		MessageInfos:      file_search_v1_search_proto_msgTypes,
	}.Build()
	File_search_v1_search_proto = out.File
	file_search_v1_search_proto_goTypes = nil
	file_search_v1_search_proto_depIdxs = nil
}
