// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: bff/v1/bff.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlogBff_GetFullUserProfile_FullMethodName = "/api.bff.v1.BlogBff/GetFullUserProfile"
)

// BlogBffClient is the client API for BlogBff service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogBffClient interface {
	// 获取完整的用户个人主页数据
	GetFullUserProfile(ctx context.Context, in *GetFullUserProfileRequest, opts ...grpc.CallOption) (*GetFullUserProfileReply, error)
}

type blogBffClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogBffClient(cc grpc.ClientConnInterface) BlogBffClient {
	return &blogBffClient{cc}
}

func (c *blogBffClient) GetFullUserProfile(ctx context.Context, in *GetFullUserProfileRequest, opts ...grpc.CallOption) (*GetFullUserProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFullUserProfileReply)
	err := c.cc.Invoke(ctx, BlogBff_GetFullUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogBffServer is the server API for BlogBff service.
// All implementations must embed UnimplementedBlogBffServer
// for forward compatibility.
type BlogBffServer interface {
	// 获取完整的用户个人主页数据
	GetFullUserProfile(context.Context, *GetFullUserProfileRequest) (*GetFullUserProfileReply, error)
	mustEmbedUnimplementedBlogBffServer()
}

// UnimplementedBlogBffServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlogBffServer struct{}

func (UnimplementedBlogBffServer) GetFullUserProfile(context.Context, *GetFullUserProfileRequest) (*GetFullUserProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFullUserProfile not implemented")
}
func (UnimplementedBlogBffServer) mustEmbedUnimplementedBlogBffServer() {}
func (UnimplementedBlogBffServer) testEmbeddedByValue()                 {}

// UnsafeBlogBffServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogBffServer will
// result in compilation errors.
type UnsafeBlogBffServer interface {
	mustEmbedUnimplementedBlogBffServer()
}

func RegisterBlogBffServer(s grpc.ServiceRegistrar, srv BlogBffServer) {
	// If the following call panics, it indicates UnimplementedBlogBffServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlogBff_ServiceDesc, srv)
}

func _BlogBff_GetFullUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFullUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogBffServer).GetFullUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogBff_GetFullUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogBffServer).GetFullUserProfile(ctx, req.(*GetFullUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlogBff_ServiceDesc is the grpc.ServiceDesc for BlogBff service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlogBff_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bff.v1.BlogBff",
	HandlerType: (*BlogBffServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFullUserProfile",
			Handler:    _BlogBff_GetFullUserProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bff/v1/bff.proto",
}
