// Code generated by Wire. DO NOT EDIT.

//go:generate go tool wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/satiu123/GoPalette/app/search/service/internal/biz"
	"github.com/satiu123/GoPalette/app/search/service/internal/conf"
	"github.com/satiu123/GoPalette/app/search/service/internal/data"
	"github.com/satiu123/GoPalette/app/search/service/internal/server"
	"github.com/satiu123/GoPalette/app/search/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	searchRepo := data.NewSearchRepo(dataData, logger)
	postSourceRepo := data.NewPostSourceRepo(dataData, logger)
	searchUsecase := biz.NewSearchUsecase(searchRepo, postSourceRepo, logger)
	searchService := service.NewSearchService(searchUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, searchService, logger)
	httpServer := server.NewHTTPServer(confServer, searchService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
