// Code generated by Wire. DO NOT EDIT.

//go:generate go tool wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/satiu123/GoPalette/app/search/service/internal/biz"
	"github.com/satiu123/GoPalette/app/search/service/internal/conf"
	"github.com/satiu123/GoPalette/app/search/service/internal/data"
	"github.com/satiu123/GoPalette/app/search/service/internal/server"
	"github.com/satiu123/GoPalette/app/search/service/internal/service"
	"github.com/satiu123/GoPalette/pkg/opentelemetry"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger, serviceName opentelemetry.ServiceName) (*kratos.App, func(), error) {
	client, err := NewEtcdClient(registry)
	if err != nil {
		return nil, nil, err
	}
	etcdRegistry := NewRegistry(client)
	postClient := data.NewPostClient(etcdRegistry, confData)
	dataData, cleanup, err := data.NewData(confData, logger, postClient)
	if err != nil {
		return nil, nil, err
	}
	searchRepo := data.NewSearchRepo(dataData, logger)
	postSourceRepo := data.NewPostSourceRepo(dataData, logger)
	searchUsecase := biz.NewSearchUsecase(searchRepo, postSourceRepo, logger)
	postIndexConsumer := data.NewPostIndexConsumer(dataData)
	searchService := service.NewSearchService(searchUsecase, postIndexConsumer, logger)
	health := server.NewHealthEngine(dataData)
	int64Counter := opentelemetry.NewRequestCounter(serviceName)
	float64Histogram := opentelemetry.NewSecondsHistogram(serviceName)
	grpcServer := server.NewGRPCServer(confServer, searchService, logger, health, int64Counter, float64Histogram)
	httpServer := server.NewHTTPServer(confServer, searchService, logger, health, int64Counter, float64Histogram)
	app := newApp(logger, grpcServer, httpServer, etcdRegistry)
	return app, func() {
		cleanup()
	}, nil
}
