// Code generated by Wire. DO NOT EDIT.

//go:generate go tool wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/satiu123/GoPalette/app/comment/service/internal/biz"
	"github.com/satiu123/GoPalette/app/comment/service/internal/conf"
	"github.com/satiu123/GoPalette/app/comment/service/internal/data"
	"github.com/satiu123/GoPalette/app/comment/service/internal/server"
	"github.com/satiu123/GoPalette/app/comment/service/internal/service"
	"github.com/satiu123/GoPalette/pkg/opentelemetry"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, registry *conf.Registry, logger log.Logger, serviceName opentelemetry.ServiceName) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	commentRepo := data.NewCommentRepo(dataData, logger)
	rateLimitRepo := data.NewRateLimitRepo(dataData)
	commentEventPublisher := data.NewCommentEventPublisher(dataData)
	commentUsecase := biz.NewCommentUsecase(commentRepo, rateLimitRepo, commentEventPublisher, logger)
	commentService := service.NewCommentService(commentUsecase, logger)
	health := server.NewHealthEngine(dataData)
	int64Counter := opentelemetry.NewRequestCounter(serviceName)
	float64Histogram := opentelemetry.NewSecondsHistogram(serviceName)
	grpcServer := server.NewGRPCServer(confServer, auth, commentService, logger, health, int64Counter, float64Histogram)
	httpServer := server.NewHTTPServer(confServer, auth, commentService, logger, health, int64Counter, float64Histogram)
	client, err := NewEtcdClient(registry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	etcdRegistry := NewRegistry(client)
	app := newApp(logger, grpcServer, httpServer, etcdRegistry)
	return app, func() {
		cleanup()
	}, nil
}
